### ISSUE TITLE
Find a better name/brand

### ISSUE THREAD

**Issue by apeacox** [nebulab/gcommerce#1]

**Comment by olistik** [comment]
Nebulab refers to stars & co.
Gcommerce is not a rewrite of Spree, nor they're completely unrelated.
It's more of a shining rebirth process that spawns with respect and thanks to the source.
A *Nova*.
[Nova on Wikipedia](https://en.wikipedia.org/wiki/Nova)

**Comment by apeacox** [comment]
:+1: :100:  I like it a lot!

Nova Commerce, with namespace Nova :-)

@mtylty @kennyadsl @AlessioRocco ???

**Comment by juandazapata** [comment]
Drop the "commerce" part, just **Nova**

**Comment by kennyadsl** [comment]
it just works :+1:

**Comment by mtylty** [comment]
:+1: :100:
